### ISSUE TITLE
More of a Question then an Issue

### ISSUE THREAD

**Issue by aiddenkeli** [0xfffffffa/DEFCON-18-Android-rootkit-Mindtrick#1]
I am trying to find a better solution than Meterpreter for mobile pen-testing engagements. Short of modifying the source for android/meterpreter/reverse_https there is no good solution that doesn't put a icon on the phone and maintain persistence. Its rare but I do have clients what want to see what can be gleaned from long term (2 weeks) access to some company phones. I know this is from research in 2010 so I have to ask, is this still valid today?

Sadly my coding skills are lacking (currently learning python which unfortunately doesn't help here) or I would just roll my own. (Let the script kiddy jokes ensue)

Thank you in advance for any help or direction if there is a better path!

**Comment by 0xfffffffa** [comment]
Yup, this is just as relevant today as it was back in 2010 and due to the level at which it operates (kernel) it would not show any tell-tail signs of compromise (mysterious icons etc)

Regards,
CP

**Comment by aiddenkeli** [comment]
Thank you! Now I will attempt to compile for an S5. Thanks again.
